/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as WebServerImport } from './routes/web-server';
import { Route as BcryptImport } from './routes/bcrypt';
import { Route as IndexImport } from './routes/index';

// Create/Update Routes

const WebServerRoute = WebServerImport.update({
    id: '/web-server',
    path: '/web-server',
    getParentRoute: () => rootRoute,
} as any);

const BcryptRoute = BcryptImport.update({
    id: '/bcrypt',
    path: '/bcrypt',
    getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/': {
            id: '/';
            path: '/';
            fullPath: '/';
            preLoaderRoute: typeof IndexImport;
            parentRoute: typeof rootRoute;
        };
        '/bcrypt': {
            id: '/bcrypt';
            path: '/bcrypt';
            fullPath: '/bcrypt';
            preLoaderRoute: typeof BcryptImport;
            parentRoute: typeof rootRoute;
        };
        '/web-server': {
            id: '/web-server';
            path: '/web-server';
            fullPath: '/web-server';
            preLoaderRoute: typeof WebServerImport;
            parentRoute: typeof rootRoute;
        };
    }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute;
    '/bcrypt': typeof BcryptRoute;
    '/web-server': typeof WebServerRoute;
}

export interface FileRoutesByTo {
    '/': typeof IndexRoute;
    '/bcrypt': typeof BcryptRoute;
    '/web-server': typeof WebServerRoute;
}

export interface FileRoutesById {
    __root__: typeof rootRoute;
    '/': typeof IndexRoute;
    '/bcrypt': typeof BcryptRoute;
    '/web-server': typeof WebServerRoute;
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths: '/' | '/bcrypt' | '/web-server';
    fileRoutesByTo: FileRoutesByTo;
    to: '/' | '/bcrypt' | '/web-server';
    id: '__root__' | '/' | '/bcrypt' | '/web-server';
    fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    BcryptRoute: typeof BcryptRoute;
    WebServerRoute: typeof WebServerRoute;
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    BcryptRoute: BcryptRoute,
    WebServerRoute: WebServerRoute,
};

export const routeTree = rootRoute
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bcrypt",
        "/web-server"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bcrypt": {
      "filePath": "bcrypt.tsx"
    },
    "/web-server": {
      "filePath": "web-server.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
