name: build

on:
    push:
        branches:
            - main

jobs:
    main:
        name: Build artifacts and push to main-build branch

        runs-on: ubuntu-latest

        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  # without this, "git checkout main-build" will fail because the main-build branch is not present in the local repository.
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: yarn

            - run: git config --local user.email "build.yml[bot]@example.com" # fake user email for pushing build
            - run: git config --local user.name "build.yml[bot]" # fake user name for pushing build

              # create a temporary "main-build-temp" branch here, so do not create "main-build-temp" branch in your repository and push it.
            - run: git checkout -b main-build-temp

            - run: cat ./.gitignore

            - name: Comment out dist/ from .gitignore
              run: "sed -i 's/dist\\//# dist\\//g' ./.gitignore"

            - run: cat ./.gitignore

            - run: yarn
            - run: yarn build

            - run: git add --all

            - run: 'git commit -m "build: comment out dist/ in .gitignore and build artifacts"'

            - run: git checkout main-build

            # 当初は "git merge -s theirs main-build-temp" に相当することがしたかったため、main-build-temp ブランチで "git merge -s ours main-build" を実行して main-build ブランチを fast-forward merge することで再現しようとしたが、コミットグラフが複雑になるため、単純に -X theirs で merge することにした。
            - run: git merge -X theirs --no-ff --no-commit main-build-temp

            # by default, the message of merge commit is "Merge branch 'main-build-temp' into main-build", so the message is changed not to include "main-build-temp".
            # if this merge is first and no --allow-empty, this job fails because there is nothing to commit.
            - run: git commit --allow-empty -m "Merge"

            # set "Allow GitHub Actions to create and approve pull requests" in the repository settings to enable pull request creation.
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v7
              with:
                  title: 'auto build (${{ github.sha }})'
                  body: |
                      main ブランチへの push を確認したため、自動的に build を実行して main-build ブランチへの PR を作成しました。

                      承認しない場合はこの PR を無視するか close してください。

                      # last commit information
                      | Name | Value |
                      |------|-------|
                      | actor   | ${{ github.actor }}                     |
                      | sha     | ${{ github.sha }}                       |
                      | message | ${{ github.event.head_commit.message }} |
                  labels: auto-build
                  branch: create-pull-request/auto-build
