name: can-install packages/api-server

on:
    pull_request:
        paths-ignore:
            - 'packages/**'
            - '!packages/api-server/**'

jobs:
    yarn:
        name: Check yarn install --production=${{matrix.is_production}} and build on Node ${{ matrix.node }}, and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        defaults:
            run:
                working-directory: ./packages/api-server
        strategy:
            matrix:
                node: ['14.x', '16.x']
                os: [ubuntu-latest, windows-latest, macos-latest]
                is_production: ['false', 'true']

        steps:
            - uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
                  cache: yarn

            - run: yarn workspaces focus --all --production

            - name: Prepare other packages
              run: yarn build
              working-directory: '.'

            - name: Build (as type checking)
              run: yarn build
