name: can-publish

on:
    pull_request:
        branches: [release]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14.x
                  registry-url: 'https://registry.npmjs.org'
                  always-auth: true
            - name: can publish
              run: npx can-npm-publish --verbose
