name: 'Close stale auto-build PRs'
on:
    schedule:
        - cron: '0 7,19 * * *'

permissions:
    contents: write # only for delete-branch option
    pull-requests: write

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v9
              with:
                  stale-pr-message: 'This PR is stale because it has `auto-build` label and it has been open 1 day with no activity. Remove stale label or this will be closed and the branch will be deleted in 1 day.'
                  days-before-pr-stale: 1
                  days-before-pr-close: 1
                  stale-pr-label: stale
                  only-pr-labels: auto-build
                  ignore-pr-updates: true
                  delete-branch: true
