name: docker-push

on:
    push:
        tags:
            - 'api/v*.*.*'

jobs:
    docker-push:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: docker build
              run: docker build -f api-server.Dockerfile -t kizahasi/flocon-api:${GITHUB_REF##*/} --build-arg branch="api/${GITHUB_REF##*/}" .
              working-directory: ./docker
            - name: docker push
              run: docker push kizahasi/flocon-api:${GITHUB_REF##*/}
