name: docker-push

on:
    push:
        tags:
            - 'api/v*.*.*'

jobs:
    docker-push:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: docker build (flocon-api)
              run: docker build -t kizahasi/flocon-api:${GITHUB_REF##*/} --build-arg branch="api/${GITHUB_REF##*/}" .
              working-directory: ./docker/api-server
            - name: docker build (flocon-api-swap256mb)
              run: docker build -t kizahasi/flocon-api-swap256mb:${GITHUB_REF##*/} --build-arg branch="api/${GITHUB_REF##*/}" .
              working-directory: ./docker/api-server-swap256mb

            - name: docker push (flocon-api)
              run: docker push kizahasi/flocon-api:${GITHUB_REF##*/}
            - name: docker push (flocon-api-swap256mb)
              run: docker push kizahasi/flocon-api-swap256mb:${GITHUB_REF##*/}
