name: prettier

on:
    push:
        branches:
            - '**'
        tags-ignore:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    # fails in windows because it uses crlf
    main:
        name: Lint and prettier on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['16.x']
                os: [ubuntu-20.04]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
                  cache: yarn

            - run: yarn

            - name: Lint
              run: yarn lint

            - name: Prettier(check)
              run: yarn prettier:base --check
