name: publish

on:
    push:
        branches:
            - release

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  registry-url: 'https://registry.npmjs.org'
                  always-auth: true
            - name: install
              run: yarn
            - name: publish
              run: yarn run publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
