name: publish 

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      - name: can publish
        run: npx can-npm-publish --verbose
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: install
        run: yarn install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: build
        run: yarn build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: publish
        run: yarn publish --access publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}