name: Checks for pull request to release

on:
    pull_request:
        branches:
            - 'release'

jobs:
    check-disclaimer:
        name: Check licenses-npm-package.txt

        runs-on: ubuntu-22.04

        steps:
            - name: List git config
              run: git config -l

            - uses: actions/checkout@v3

            - name: Use Node 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: yarn

            - run: yarn

            - name: Generate licenses disclaimer
              run: yarn generate-disclaimer

            # yarn generate-disclaimer で生成されるファイルはLFとCRLFが混在するため、改行コードを統一する処理を行っている。
            - name: Clean CRLF
              run: git config --local core.autocrlf input && git add . && git reset

            - name: Fail if not all the artifacts are OK
              uses: numtide/clean-git-action@v1
