name: release

on:
    push:
        tags:
            - 'v2*.*.*'
            - 'v3*.*.*'

jobs:
    git-diff-main-build:
        name: git diff remotes/origin/main-build

        runs-on: ubuntu-22.04

        steps:
            - name: List git config
              run: git config -l

            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Fail if not all the files are OK
              run: |
                  if [[ -n "$(git diff remotes/origin/main-build)" ]]; then
                      echo "ERROR: The project is dirty!"
                      git diff --stat remotes/origin/main-build
                    exit 1
                  else
                      echo "OK."
                  fi

    release:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - run: yarn

            - name: Build web-server
              run: yarn build
              working-directory: ./apps/web-server
            - name: mv out directory
              run: mv ./apps/web-server/out ./out
            - name: Create flocon_web_server.zip
              run: zip -r ${GITHUB_WORKSPACE}/flocon_web_server.zip ./out

            - name: Generate Dockerfile
              run: yarn run gen-flyio-dockerfile
              working-directory: ./apps/api-server
            - name: mv Dockerfile
              run: mv ./apps/api-server/flyio.Dockerfile ./Dockerfile
            - name: Create flocon_api_server_flyio.zip
              run: zip ${GITHUB_WORKSPACE}/flocon_api_server_flyio.zip ./Dockerfile

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      flocon_web_server.zip
                      flocon_api_server_flyio.zip
                  draft: true
