name: tests packages/core

on:
    pull_request:
        paths-ignore:
            - 'packages/**'
            - '!packages/core/**'

# to see more appropriate coverage, this has redis tests
jobs:
    full-test:
        name: Large test & Redis test on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./packages/core
        strategy:
            matrix:
                node: ['16.x']

        steps:
            - uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
                  cache: yarn

            # https://docs.github.com/ja/actions/using-containerized-services/creating-redis-service-containers の方法だとRedisに接続できなかったため、代わりに採用している
            - name: Start Redis
              uses: supercharge/redis-github-action@1.2.0
              with:
                  redis-version: 6

            - run: yarn

            - name: Prepare other packages
              run: yarn build
              working-directory: '.'

            - name: Test
              run: TEST_NUM_RUNS=5000 yarn test --ci --coverage --maxWorkers=2
