name: tests packages/flocon-script

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'packages/**'
            - '!packages/flocon-script/**'
    pull_request:
        paths-ignore:
            - 'packages/**'
            - '!packages/flocon-script/**'

jobs:
    main:
        name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        defaults:
            run:
                working-directory: ./packages/flocon-script
        strategy:
            matrix:
                node: ['12.x', '14.x', '16.x']
                os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
                  cache: yarn

            - run: yarn

            - name: Prepare other packages
              run: yarn build-dist
              working-directory: '.'

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test --ci --coverage --maxWorkers=2
