name: tests packages/core

on:
    pull_request:
        branches:
            - release
            - 'npm-publish'

jobs:
    full-test:
        name: Large test on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./packages/core
        strategy:
            matrix:
                node: ['16.x']

        steps:
            - uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
                  cache: yarn

            - run: yarn

            - name: Prepare packages
              run: yarn build-ci
              working-directory: '.'

            - name: Test
              run: TEST_NUM_RUNS=5000 yarn test --ci --coverage --maxWorkers=2
